export default [
    {
        id:1,
        active:true,
        name: 'شاورما دجاج وسط',
        price: '2,000',
        qt: null,
        image: 'https://tse2.mm.bing.net/th?id=OIP.5gCeZ1w6gAF_ld-15JdyLAHaE7&pid=Api&P=0&w=250&h=167',
    },
    {
        id:2,
        active:true,
        name: 'نفر قوزي عالتمن',
        price: '25,000',
        qt: null,
        image: 'https://tse4.mm.bing.net/th?id=OIP.C6nKW6N63HMiMzte0c2o1AHaFj&pid=Api&P=0&w=222&h=167',
    },
    {
        id:3,
        active:true,
        name: 'ماعون مقبلات كبير',
        price: '3,000',
        qt: null,
        image: 'https://tse1.mm.bing.net/th?id=OIP.5XAJxARL7z6G-KexinzzagHaIg&pid=Api&P=0&w=300&h=300',
    },
    {
        id:4,
        active:true,
        name: 'مياه معدنية',
        price: '1,000',
        qt: 850,
        image: 'https://www.rcinet.ca/patrimoine-asiatique-en/wp-content/uploads/sites/26/2012/05/2-Indian-food.jpg',
    },
    {
        id:5,
        active:true,
        name: 'بيتزا وسط',
        price: '10,000',
        qt: null,
        image: 'https://www.sbs.com.au/food/sites/sbs.com.au.food/files/ep8_okonomiyaki.jpg',
    },
    {
        id:6,
        active:false,
        name: 'ماعون مقبلات كبير',
        price: '3,000',
        qt: null,
        image: 'https://tse1.mm.bing.net/th?id=OIP.5XAJxARL7z6G-KexinzzagHaIg&pid=Api&P=0&w=300&h=300',
    },
    {
        id:7,
        active:false,
        name: 'مياه معدنية',
        price: '1,000',
        qt: 850,
        image: 'https://www.rcinet.ca/patrimoine-asiatique-en/wp-content/uploads/sites/26/2012/05/2-Indian-food.jpg',
    },
    
    {
        id:8,
        active:true,
        name: 'شاورما لحم',
        price: '12,000',
        qt: null,
        image: 'https://worldoddities.com/wp-content/uploads/2017/12/bison-meat-food.jpg',
    },
    {
        id:9,
        active:false,
        name: 'مياه معدنية',
        price: '1,000',
        qt: 850,
        image: 'https://www.rcinet.ca/patrimoine-asiatique-en/wp-content/uploads/sites/26/2012/05/2-Indian-food.jpg',
    },
    
    {
        id:10,
        active:true,
        name: 'شاورما لحم',
        price: '12,000',
        qt: null,
        image: 'https://worldoddities.com/wp-content/uploads/2017/12/bison-meat-food.jpg',
    },
    
]